name: deploy

on:
  push:
    branches: [ master ]
  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install NodeJS
      uses: actions/setup-node@v2-beta
      with:
        node-version: 12
      name: install surdge
      run: npm install -g surge 
      name: run surge
      run: surge ./ simple_hello_world_file.surge.sh --token ${{secrets.SURGE_TOKEN_1}}    
      
  
